
environment:
  matrix:
    - PYTHON_VERSION: "3.8"
      MINICONDA: "C:\\Miniconda36-x64"

install:
    - "%MINICONDA%\\Scripts\\activate.bat"
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda install numpy=>1.20 scipy=>1.5 matplotlib=>3.0 h5py pip setuptools pyparsing pytest pytest-cov coverage scikit-learn cython pillow pandas sqlalchemy psutil pyyaml psycopg2-binary numdifftools emcee pymatgen
    - conda install tomopy wxpython
    - conda info -a
    - conda list
    - pip install lmfit peakutils pyepics pyshortcuts termcolor sphinx dill pycifrw xraydb wxmplot wxutils

build_script:
    - python.exe setup.py install

test_script:
    - cd tests
    - python -m pytest
