image: Visual Studio 2015

environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.7"
      MINICONDA: "C:\\Miniconda37-x64"

install:
    - "%MINICONDA%\\Scripts\\activate.bat"
    - conda config --set always_yes True
    - conda config --add channels gsecars
    - conda update conda
    - conda install python=%PYTHON_VERSION% --file requirementstxt
    - conda info -a
    - "%PYTHON%\\python.exe setup.py install"

test_script:
    - cd tests
    - "%PYTHON%\\python.exe -m pytest"
