
environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda36-x64"

install:
    - "%MINICONDA%\\Scripts\\activate.bat"
    - conda config --set always_yes True
    - conda config --add channels gsecars
    - conda update conda
    - conda install python=%PYTHON_VERSION% --file requirements.txt
    - activate base
    - pip install pyside2
    - conda info -a

build_script:
    - python.exe setup.py install

test_script:
    - cd tests
    - python -m pytest
