
environment:
  matrix:
    - PYTHON_VERSION: "3.7"
      MINICONDA: "C:\\Miniconda36-x64"

install:
    - "%MINICONDA%\\Scripts\\activate.bat"
    - conda config --set always_yes True
    - conda config --add channels gsecars
    - conda update conda
    - conda info -a
    - conda create -q -n xlarch python=3.7 numpy scipy matplotlib sqlalchemy requests pandas scikit-image scikit-learn h5py wxpython yaml pyyaml pip
    - activate xlarch
    - pip install dill nose peakutils pillow psutil psycopg2 pyepics pytest silx sphinx termcolor
    - conda install -c gsecars asteval dioptas lmfit pycifrw pyfai pyshortcuts tomopy uncertainties wxutils wxmplot patchelf pango pcre


build_script:
    - python.exe setup.py install

test_script:
    - cd tests
    - python -m pytest
