# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 3.8

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/xraylarch
    - export PATH="$HOME/xraylarch/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda config --add channels gsecars
    - conda info -a

install:
    - conda create -q -n xlarch python=3.8
    - source activate xlarch
    - conda numpy scipy matplotlib h5py sqlalchemy scikit-image scikit-learn wxpython pyyaml requests pyfai patchelf pango pcre pandas wxmplot wxutils
    - pip install dill nose pytest peakutils pillow psutil psycopg2 pyepics silx sphinx termcolor xraydb lmfit asteval pycifrw pint pyshortcuts
    - python setup.py install
    - conda list

script:
    - cd tests
    - pytest
