# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 2.7
    - 3.6

before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ; fi
    - bash miniconda.sh -b -p $HOME/xraylarch
    - export PATH="$HOME/xraylarch/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - conda create -q -n testlarch python=$TRAVIS_PYTHON_VERSION numpy scipy libgfortran matplotlib
    - source activate testlarch
    - conda install six pandas nose sphinx sqlalchemy psycopg2 wxpython pip six h5py pytest
    - conda install pillow requests yaml pyyaml pango pcre psutil scikit-learn
    - conda config --add channels gsecars
    - conda install -c gsecars uncertainties asteval lmfit=0.9.12 termcolor peakutils pyepics=3.3.3 pycifrw pyshortcuts
    - conda install -c gsecars wxmplot=0.9.34 wxutils=0.2.3
    - python setup.py install
    - conda list


script:
    - cd tests
    - pytest
