package:
  name: xraylarch
  version: "0.9.32"

source:
  git_rev: 0.9.32
  git_url:  https://github.com/xraypy/xraylarch.git

requirements:
  build:
    - python
    - setuptools
    - six
    - nose
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - termcolor
    - fontconfig
    - pango
    - pcre
    - yaml
    - pillow
    - requests
    - wxpython
    - wxmplot
    - wxutils
    - termcolor
    - pyepics
    - lmfit
#    - fabio

  run:
    - python
    - setuptools
    - six
    - nose
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - h5py
    - termcolor
    - fontconfig
    - pango
    - pcre
    - yaml
    - pillow
    - requests
    - wxpython
    - wxmplot
    - wxutils
    - termcolor
    - pyepics
    - lmfit
#    - fabio

test:
  imports:
    - larch

about:
  home: http://xraypy.github.io/xraylarch/
  license: BSD
  summary: 'Data Analysis Tools for X-ray Spectroscopy'
