name: Test with Conda, Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest  
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: update miniconda
      run: |
        printenv
        set PATH=$CONDA/bin:$CONDA/condabin:$CONDA/Scripts:$PATH
        call %CONDA%\condabin\conda update -n base -yc defaults --all
        call %CONDA%\condabin\conda activate base
        call %CONDA%\condabin\conda config --set auto_activate_base true

    - name: Install conda and dependencies
      run: |
        printenv
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install python=${{ matrix.python-vesion }} numpy=>1.20 scipy=>1.5 matplotlib=>3.0 h5py pip setuptools pyparsing pytest pytest-cov coverage scikit-learn cython pillow pandas sqlalchemy psutil pyyaml psycopg2-binary numdifftools emcee pymatgen tomopy wxpython
        conda info -a
        conda list
    - name: Install xraylarch
      run: |
        pip install lmfit peakutils pyepics pyshortcuts termcolor sphinx dill pycifrw xraydb wxmplot wxutils
        python setup.py install
    - name: Run test suite
      run: |
        cd tests
        pytest
